eureka:
  client:
    service-url:
      defaultZone: http://localhost:10999/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<remaining>.*), /$\{remaining}
        - id: holiday
          uri: lb://HOLIDAY-SERVER
          predicates:
            - Path=/calendar/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
  application:
    name: Gateway
